### ISSUE TITLE
Guide how to create AWS CodeBuild

### ISSUE THREAD

**Issue by terkin** [zoellner/sharp-heic-lambda-layer#14]
Hi, I tried to build it with AWS CodeBuild - tried S3 as source but it keep saying that it cant find file/ AccessDenied - I tried to upload zip with this repo and give it public permissions, not sure what I am doing wrong

**Comment by zoellner** [comment]
please see https://github.com/zoellner/sharp-heic-lambda-layer/issues/2#issuecomment-964208097 for a note on how to setup CodeBuild
