### ISSUE TITLE
Error class "icc_transform" not found

### ISSUE THREAD

**Issue by williamccrobinson** [zoellner/sharp-heic-lambda-layer#16]
For certain images with particular icc profiles, sharp seems to want to do transform the icc profile, causing the following error:
```
VipsOperation: class "icc_transform" not found
```

As a result, sharp crashes and the image does not get processed. Adding `lcms2-devel` to the vips build deps resolves the problem.

I will create a PR with the proposed fix if this is something desirable to have in the repo @zoellner

**Comment by zoellner** [comment]
Thank you, just noticed the error for the first time as well. Do you happen to have a sample image you can share?
Note to self: should start adding test cases
