### ISSUE TITLE
VipsOperation: class "heifsave_buffer" not found

### ISSUE THREAD

**Issue by Dimitris24sta23** [zoellner/sharp-heic-lambda-layer#19]
Hello,

I have succesfully deployed the code to a layer with CodeBuild.
The stack was completed creating the code in an s3Bucket and the layer.

![image](https://user-images.githubusercontent.com/4387685/230033164-3f48622e-9c3a-45be-8eb1-fe398780a654.png)

I've attached the layer to my function but when i try to load a test.heic image it gives a
`VipsOperation: class "heifsave_buffer" not found`
![image](https://user-images.githubusercontent.com/4387685/230033471-e71e28d4-dc51-4747-93c6-bf89512fc80f.png)

Jpegs & webp transformation works okay

I also found this to be relative https://github.com/libvips/libvips/discussions/2340

Thanks

**Comment by Dimitris24sta23** [comment]
@zoellner I think it's the dependecies.
Adding .heif({ compression: 'hevc' }) doesen't work.
I guess it's something around this: https://github.com/libvips/libvips/discussions/2340#discussioncomment-979062

It throws the `VipsOperation: class "heifsave_buffer" not found` if i try .toBuffer() when the image is still in .heic (So it tries to write it)
If i read it and transform it to jpeg and then .toBuffer() then i get the picture.
It's not bothering me much as i only want to read .heic

Thanks for your work and your quick reply.

**Comment by zoellner** [comment]
closing this since it is related to not having the libraries included for writing heic files. Other tickets cover this.
