### ISSUE TITLE
Add x265 lib

### ISSUE THREAD

**Issue by zoellner** [zoellner/sharp-heic-lambda-layer#23]
This would allow to write HEIC files as well

I think this should be the source code to build from: https://bitbucket.org/multicoreware/x265_git/src/master/
With build instructions here: https://bitbucket.org/multicoreware/x265_git/wiki/Home
this should also address #19 

note that x265 is GPL. An alternative to x265 is kvazaar (BSD).

**Comment by zoellner** [comment]
Check https://github.com/libvips/libvips/discussions/2340#discussioncomment-979057 for instructions on how to get libvips with heic support into AL2

**Comment by mvn-locnguyen-dn** [comment]
@zoellner  I installed x265 library 
	git clone https://bitbucket.org/multicoreware/x265_git.git
	cd x265_git && cmake source && make && make install
but install libheif config
configure: libde265 decoder: yes
configure: libx265 encoder: no
