### ISSUE TITLE
Support for GIFs

### ISSUE THREAD

**Issue by pistachiomatt** [zoellner/sharp-heic-lambda-layer#4]
Thanks for an amazing repo! I've tried six other repos and yours is the only one that works flawlessly out of the box.

I was hoping because this builds libvips from source that this Sharp has GIF support in addition to HEIC support. It appears it doesn't as it returns the following error:

> GIF output requires libvips with support for ImageMagick

I see a package `giflib-devel` is installed. What can I amend to have GIF support?

**Comment by zoellner** [comment]
Glad to hear that it works for you as well. 

It sounds like sharp is adding gif support in the next release: https://github.com/lovell/sharp/issues/3013
It sounds like it is a bigger undertaking and involves some API changes as well. So I'd probably wait until that is released and then update this repo accordingly. 
If you need support sooner your best bet is probably to monitor the development in the sharp repo and merge the changes related to gif into this repo.

**Comment by xtrinch** [comment]
Hi, I've had the same issue, and https://github.com/zoellner/sharp-heic-lambda-layer/pull/12, which upgrades sharp, worked for me out of the box
