### ISSUE TITLE
CloudFront Lambda@Edge aren't supported

### ISSUE THREAD

**Issue by hakimscode** [zoellner/sharp-heic-lambda-layer#5]
Hello, Im trying to use this layer to a Lambda Edge. When I adding a trigger to a CloudFront it failed and it says `Layers aren't supported`

Did anyone face the same issue?

Edited: 
seems like Lambda Edge doesn't support layers yet for now. Cmiiw

**Comment by zoellner** [comment]
That is a known limitation of Lambda@Edge, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html
Closing this since not related to this repo
