### ISSUE TITLE
How to install libx265 I try many solution but always fail

### ISSUE THREAD

**Issue by dogrocker** [zoellner/sharp-heic-lambda-layer#7]
Hello, Thanks for sharing this build tools.

I've fork you repo to make Actions workflows to create layer file, But I need "heifsave_buffer()" to save heic image from shap resize to same file format

I try many solution to add libx265 but it always fail some not fail but in lib folder there is no libx265.so

Here is my Makefile
https://github.com/dogrocker/sharp-heic-lambda-layer/blob/main/layer/Makefile

Thanks for help.

**Comment by dogrocker** [comment]
Finally done example in my link.

**Comment by SongMarco** [comment]
@dogrocker Thank you for your documentation. I've managed to find your solution and also fixed my issue, too.

**Comment by natuan62** [comment]
Thanks for your doc @dogrocker helped me!!!

**Comment by natuan62** [comment]
Time to excute

```
const convert = require("heic-convert");
const sharp = require("sharp");

console.time('test1');
          const convertedFile2 = await convert({
            buffer: s3File.Body,
            format: "JPEG",
            quality: 1,
          });
          console.timeEnd('test1');

          console.time('test2');
          const convertedFile2 = await sharp(s3File.Body)
          .clone()
          .toFormat("jpeg")
          .jpeg({
            quality: 100,
            mozjepg: true,
          })
          .toBuffer();
          console.timeEnd('test2');
```

```
2022-12-19T08:46:34.404Z		INFO	test1: 7.840s
2022-12-19T08:46:35.592Z		INFO	test2: 1.187s
```
